### ISSUE TITLE
Blender won't recognize the plugin.

### ISSUE THREAD

**Issue by Jnanibhad** [emd4600/SporeModder-Blender-Addons#2]
i followed all instructions given to me by not only this: https://github.com/Emd4600/SporeModder-Blender-Addons#installation

but also the help given by rob55rod on discord.

blender simply won't realize that i've installed the addon linked on this page: https://github.com/Emd4600/SporeModder-Blender-Addons/releases/tag/v2.0

i desperately need this addon to work as otherwise my upcoming machinema will be next to impossible. please get back to me as soon as possible. 

(yes i have worked with the previous versions of both this addon and blender.)

**Comment by emd4600** [comment]
Manual installation can cause problems. I must update the installation instructions as the addon can be installed searching the `.zip` in the Blender addons dialog.
