### ISSUE TITLE
Cannot import animations for certain parts

### ISSUE THREAD

**Issue by emd4600** [emd4600/SporeModder-Blender-Addons#6]
Importing `ce_weapon_range_solid_02.rw4` and `..._03.rw4` throws up this error:

![](https://media.discordapp.net/attachments/480030600351318017/677984053458239527/b1a052863573ba7b3ddf946391794181.png)

**Comment by MADPSI** [comment]
The bug also seems to affect several vehicle parts. I'll write up an exact list shortly as soon as I finish testing them.
